### ISSUE TITLE
1.5.1版安装win2012r2不能自动重启,ip也不是在设备详情设定的ip

### ISSUE THREAD

**Issue by wanghy8166** [idcos/osinstall#21]
1.5.1版安装win2012r2不能自动重启,ip也不是在设备详情设定的ip

如下图
![image](https://user-images.githubusercontent.com/19486774/63205603-71ba9400-c0d9-11e9-8874-eb85cfd1519b.png)

我的环境是在esxi里建的一个虚拟机做Cloudboot的服务器，安装cloudboot-1.5.1-1.x86_64.rpm后各服务都启动正常，利用它安装centos7.6一切正常，安装win2012r2时，在最后阶段提示重启，但实际却无法完成重启，停留在了上图位置，手工重启后，系统能进入，ip地址不是在设备详情设定的ip，是自动获取的，请问如何处理上述2个问题？

**Comment by wangsu728** [comment]
最后一行拷贝文件失败，手动执行这一条命令试试。可能是 samba 服务对应的目录没有权限导致

**Comment by wanghy8166** [comment]
最后一行拷贝，将c:/firstboot更换成c:\firstboot后手动执行是成功的，然后手动重启，后续是顺利的。
但是我不知道怎么修复这个问题？

**Comment by wangsu728** [comment]
如果一定要改成 c:\firstboot，那么需要修改代码重新编译，但不一定是这里的问题

**Comment by wanghy8166** [comment]
能不能教我改哪里，怎么编译，替换哪几个文件，教方法给我，我来操作。

**Comment by wangsu728** [comment]
修改的代码：https://github.com/idcos/osinstall-server/blob/master/src/idcos.io/osinstall/cmd/pe-agent/main.go
编译的方法：https://github.com/idcos/osinstall-server
编译后替换 winpe 中的 %windir%/system32/peconfig.exe

**Comment by wanghy8166** [comment]
修改main.go文件，将c:/firstboot更换成c:\\\firstboot后编译，解决问题。
用编译出来的pe-agent.exe替换peconfig.exe
用WimTool.EXE重新打包boot.wim，过程中需要替换peconfig.exe
用UltraISO.exe重新打包winpe.iso，过程中需要替换boot.wim
本次提供打包后的winpe.iso

链接：https://pan.baidu.com/s/1TCMELjZNmMUWCmyUaSb4SA 
提取码：evgk 
复制这段内容后打开百度网盘手机App，操作更方便哦
