### ISSUE TITLE
请问下当前版本支持uefi装机吗

### ISSUE THREAD

**Issue by niweitong** [idcos/osinstall#25]

**Comment by kedadiannao220** [comment]
开源版本目前不支持，[企业版本]((http://www.idcos.com/products/cloudboot))支持

**Comment by xibolun** [comment]
支持的

**Comment by niweitong** [comment]
我测试了社区版1.5.1的，好像不支持uefi，后续是有迭代吗？

**Comment by xibolun** [comment]
开源的暂时没有精力维护了，可以加qq群讨论   120556005
