### ISSUE TITLE
安装完访问URL报错

### ISSUE THREAD

**Issue by kr521** [idcos/osinstall#3]
Server端url检查正常返回JSON串。
访问49152端口，正常返回json。

访问dashboard报错
http://172.18.21.101:4200/api/osinstall/v1/device/getNumByStatus 404 NOT FOUND

直接访问404的URL报错如下
Cannot GET /api/osinstall/v1/device/getNumByStatus 

通过firebug发现很多警告都是vendor.js里的。
是不是我哪里安装的有问题？
系统 centos 6.7 
{ npm: '2.14.9',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.9',
  openssl: '1.0.1q',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }

**Comment by yunji-devin** [comment]
你好，Server端默认监听8083端口，测试可直接测8083：
http://localhost:8083/api/osinstall/v1/device/getNetworkBySn?sn=xxx&type=json
Output:
{
  "Content": "",
  "Message": "record not found",
  "Status": "error"
}

如Server端没问题，ember启动时需代理到后端：
ember server --proxy=http://localhost:8083/

**Comment by kr521** [comment]
THX,已经OK。
