### ISSUE TITLE
Firefox中显示空白页

### ISSUE THREAD

**Issue by liucy1983** [idcos/osinstall#4]
当前浏览器只支持Chrome，建议在文档中说明

**Comment by liyifan1024** [comment]
http://192.168.0.1/#/dashboard/main

**Comment by liyifan1024** [comment]
http://192.168.0.1/#/dashboard/main

**Comment by xibolun** [comment]
这个链接是你本地的，无法打开；
空白的问题看看是不是火墙没有关闭，后端地址访问不了
