### ISSUE TITLE
gb如何在无法访问外网的情况下安装？是否可以提供已经编译好的os-install-server的可执行安装文件

### ISSUE THREAD

**Issue by elven2016** [idcos/osinstall#6]
由于无法访问外网，请看看如何在内网安装gb，另外os-install-server是否可以提供已经编译好的可执行文件？

**Comment by yunji-devin** [comment]
@elven2016 编译好的可执行文件我们已经放出来了，请看这里：http://idcos.com/download.html

**Comment by yunji-devin** [comment]
@elven2016 有其他问题，欢迎加入QQ群：120556005

**Comment by ygmpkk** [comment]
@elven2016 `gb`是一个go的build工具，`gb`需要在线安装，安装gb用这个命令 `go get github.com/constabulary/gb/...` 。再运行  `gb build` 即可编译完成，二进制文件都在项目的bin目录下

**Comment by elven2016** [comment]
@ygmpkk 这个是在线安装的命令，无法访问外网的情况下就安装不了
